obj-$(CONFIG_OPLUS_FEATURE_LOWMEM_DBG)	+= lowmem_dbg/
obj-$(CONFIG_OPLUS_WAKELOCK_PROFILER)	+= owakelock/
obj-y					+= oplus_healthinfo/
obj-$(CONFIG_OPLUS_SYSTEM_KERNEL)	+= system/
obj-$(CONFIG_HORAE_THERMAL_SHELL)	+= thermal/
